version: '2'
services:
    deepstream:
        image: deepstreamio/deepstream.io:latest
        ports:
            - "6020:6020"
            - "6021:6021"
        volumes:
            - ./conf:/etc/deepstream
